### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by putztzu** [guiajlopes/generator-druproject#1]
Found this interesting project.
Installed it, but the internal documentation is unchanged, which recommends and describes deploying on Apache.
Is a nodejs (possibly Express) webserver config file included somewhere, or should I drop into the website root a nodejs webserver configuration file of my own making?

Thx;

**Comment by guiajlopes** [comment]
it just create the folder structure to Drupal 7 ou Drupal 8. This project is not responsible to the webserver it's just a generator.

you can run like this:
```
npm install -g yo generator-druproject
yo druproject
```

you will need to answer some questions and after that it will generate the project to you. It's just an boilerplate
